### ISSUE TITLE
Replace old HotRod index annotation with new one

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#12493]
Infinispan introduced new annotations in https://issues.redhat.com/browse/ISPN-13842, we should use these instead of the old one

**Comment by mhajas** [comment]
This is weird. I believe ISPN 14 should support also the old annotations. I think we should update both within #14925. We can try to update this together?

**Comment by martin-kanis** [comment]
It is related somehow to the annotations. If I remove following imports and related annotations from a HotRodEntity, I have less errors:

```
import org.infinispan.protostream.annotations.AutoProtoSchemaBuilder;
import org.infinispan.protostream.annotations.ProtoDoc;
import org.infinispan.protostream.annotations.ProtoField;
```

**Comment by martin-kanis** [comment]
I narrowed it down to `AutoProtoSchemaBuilder` and this code block:
```
@AutoProtoSchemaBuilder(
            includeClasses = {
                    HotRodGroupEntity.class
            },
            schemaFilePath = "proto/",
            schemaPackageName = CommonPrimitivesProtoSchemaInitializer.HOT_ROD_ENTITY_PACKAGE,
            dependsOn = {CommonPrimitivesProtoSchemaInitializer.class}
    )

```
Do you have any idea what the problem might be?

**Comment by hmlnarik** [comment]
> All errors are like this:
> 
> ```
> /home/mkanis/workspace/keycloak/model/map-hot-rod/target/generated-sources/annotations/org/keycloak/models/map/storage/hotRod/singleUseObject/HotRodSingleUseObjectEntitySchemaImpl.java:[12,29] cannot find symbol
> [ERROR]   symbol:   class Generated
> [ERROR]   location: package javax.annotation.processing
> ```

This is caused by #15566
