### PR TITLE
updating to quarkus 3.31.1

### LINKED ISSUE #45337: Upgrade to Quarkus 3.31
### Description

Upgrade once the [release](https://github.com/quarkusio/quarkus/releases/tag/3.31.0) is available.

### PR DESCRIPTION
**Pull request by shawkins**
closes: #45576

Summary of changes:
- an operator sdk release, 7.5.0.CR1, may address the build time error affecting the operator tests
- the rest of testcontainers 1.x needed to be removed
- we need to manage the microprofile-metrics-api dependency version
- we need to exclude the quarkus bootstrap jar to prevent tests from thinking trace is enabled
- the logging context for hibernate jpa debug messages changed

### CODE REVIEW

**Comment by metacosm** [comment]
> closes: #45576
> 
> Failing just as quarkus-next is - it appears that the java operator sdk may not be appropriately updated yet.
> 
> @metacosm is the operator sdk ready for quarkus 3.31.0?

Yes but we don't have a release for it yet. I can do it now, if needed, though.

**Comment by shawkins** [comment]
> Yes but we don't have a release for it yet. I can do it now, if needed, though.

@metacosm yes please. There seems to be an incompatiblity currently:

```
Error:  Failed to execute goal io.quarkus:quarkus-maven-plugin:3.31.0.CR1:build (default) on project keycloak-operator: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
Error: [ERROR] 	[error]: Build step io.quarkiverse.operatorsdk.deployment.AddNamespaceEnvVarBuildStep#addNamespaceEnvVar threw an exception: java.lang.NoSuchMethodError: 'io.quarkus.kubernetes.spi.KubernetesEnvBuildItem io.quarkus.kubernetes.spi.KubernetesEnvBuildItem.createSimpleVar(java.lang.String, java.lang.String, java.lang.String, boolean[])'
Error:  	at io.quarkiverse.operatorsdk.deployment.AddNamespaceEnvVarBuildStep.lambda$addNamespaceEnvVar$0(AddNamespaceEnvVarBuildStep.java:15)
Error:  	at java.base/java.util.HashMap$Values.forEach(HashMap.java:1073)
Error:  	at io.quarkiverse.operatorsdk.deployment.AddNamespaceEnvVarBuildStep.addNamespaceEnvVar(AddNamespaceEnvVarBuildStep.java:12)
Error:  	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
Error:  	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:898)
Error:  	at io.quarkus.builder.BuildContext.run(BuildContext.java:255)
```

**Comment by metacosm** [comment]
> > Yes but we don't have a release for it yet. I can do it now, if needed, though.
> 
> @metacosm yes please. There seems to be an incompatiblity currently:
> 
> ```
> Error:  Failed to execute goal io.quarkus:quarkus-maven-plugin:3.31.0.CR1:build (default) on project keycloak-operator: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
> Error: [ERROR] 	[error]: Build step io.quarkiverse.operatorsdk.deployment.AddNamespaceEnvVarBuildStep#addNamespaceEnvVar threw an exception: java.lang.NoSuchMethodError: 'io.quarkus.kubernetes.spi.KubernetesEnvBuildItem io.quarkus.kubernetes.spi.KubernetesEnvBuildItem.createSimpleVar(java.lang.String, java.lang.String, java.lang.String, boolean[])'
> Error:  	at io.quarkiverse.operatorsdk.deployment.AddNamespaceEnvVarBuildStep.lambda$addNamespaceEnvVar$0(AddNamespaceEnvVarBuildStep.java:15)
> Error:  	at java.base/java.util.HashMap$Values.forEach(HashMap.java:1073)
> Error:  	at io.quarkiverse.operatorsdk.deployment.AddNamespaceEnvVarBuildStep.addNamespaceEnvVar(AddNamespaceEnvVarBuildStep.java:12)
> Error:  	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
> Error:  	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:898)
> Error:  	at io.quarkus.builder.BuildContext.run(BuildContext.java:255)
> ```

Interesting, I haven't seen that error when upgrading to 3.31.0.CR1. I'm not even sure why it's reporting an error there because we're not calling a `createSimpleVar(String, String, String, boolean[])` method at all. We're calling `KubernetesEnvBuildItem.createSimpleVar(String, String, String)` at that spot…

**Comment by metacosm** [comment]
We've release 7.5.0.CR1 targeting Quarkus 3.31.0.CR1.

**Comment by shawkins** [comment]
> We've release 7.5.0.CR1 targeting Quarkus 3.31.0.CR1.

Thank you @metacosm !

**Comment by shawkins** [comment]
Hopefully the JOSDK update will address the operator failures.

The logging failure in the IT tests has been addressed  - also https://github.com/keycloak/keycloak/issues/45642 was captured.

This still leaves 3 other failures.

cc @keycloak/cloud-native

**Comment by shawkins** [comment]
@mabartos added another commit to address the trace logging - there's been some kind of change where we now have quarkus-bootstrap-runner as a transitive dependency in keycloak services and that cause the log initializer to default to showing trace enabled. Added an exclusion, but a quarkus fix may be applicable too.

cc @keycloak/cloud-native

**Comment by metacosm** [comment]
Looks like https://github.com/keycloak/keycloak/pull/45679 addresses the issue with QOSDK.

**Comment by shawkins** [comment]
> Looks like https://github.com/keycloak/keycloak/pull/45679 addresses the issue with QOSDK.

Thank you @metacosm. Do you know what the timeline should look like for this to be included? Or should we just go ahead and move forward with temporary version override for now?

**Comment by metacosm** [comment]
> > Looks like #45679 addresses the issue with QOSDK.
> 
> Thank you @metacosm. Do you know what the timeline should look like for this to be included? Or should we just go ahead and move forward with temporary version override for now?

The goal is to get the final version in the 3.31 platform by next week. Since it seems that the issue is addressed with CR1, we will go ahead with the final release so that we can get included in the 3.31 platform. /cc @xstefank

**Comment by shawkins** [comment]
@keycloak/cloud-native moved to 3.31.1, but not quite there yet. There's a javascript test failure and the storage tests are failing due to a low-level issue:

```
2026-01-28T20:54:45.6689676Z Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.forEach(java.util.function.Consumer)" because the return value of "org.hibernate.sql.exec.spi.LoadedValuesCollector.getCollectedCollections()" is null
2026-01-28T20:54:45.6690234Z 	at org.hibernate.sql.exec.internal.lock.LockingHelper.logLoadedValues(LockingHelper.java:478)
2026-01-28T20:54:45.6690943Z 	at org.hibernate.sql.exec.internal.lock.FollowOnLockingAction.performPostAction(FollowOnLockingAction.java:102)
2026-01-28T20:54:45.6691748Z 	at org.hibernate.sql.exec.internal.JdbcSelectWithActions.performPostAction(JdbcSelectWithActions.java:122)
2026-01-28T20:54:45.6701603Z 	at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.doExecuteQuery(JdbcSelectExecutorStandardImpl.java:220)
2026-01-28T20:54:45.6702438Z 	at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.executeQuery(JdbcSelectExecutorStandardImpl.java:100)
2026-01-28T20:54:45.6702986Z 	at org.hibernate.sql.exec.spi.JdbcSelectExecutor.executeQuery(JdbcSelectExecutor.java:63)
2026-01-28T20:54:45.6703447Z 	at org.hibernate.sql.exec.spi.JdbcSelectExecutor.list(JdbcSelectExecutor.java:137)
```

I'll look into that more tomorrow.

**Comment by mabartos** [comment]
@shawkins Accidentally rerun the model tests. 

First attempt: https://github.com/keycloak/keycloak/actions/runs/21454033071/attempts/1?pr=45612

**Comment by mabartos** [comment]
@shawkins As seen in the stack trace, the NPE is thrown in the [LockingHelper](https://github.com/hibernate/hibernate-orm/blob/main/hibernate-core/src/main/java/org/hibernate/sql/exec/internal/lock/LockingHelper.java#L467), where the loaded values are printed when the debug level is set for the `org.hibernate.orm.sql.exec`. 

The NPE is thrown (the code is executed) in our tests when a realm is deleted. 

```java
public static void logLoadedValues(LoadedValuesCollector collector) {
		if ( SQL_EXEC_LOGGER.isDebugEnabled() ) {
			var summary = new StringBuilder();
			summary.append( "  Loaded entities:\n" );
			collector.getCollectedEntities().forEach( (reg) -> {
				summary.append( String.format( "    - %s#%s\n",
						reg.entityDescriptor().getEntityName(),
						reg.entityKey().getIdentifier() ) );
			} );
```

Everywhere where the collectedEntities and collectedCollections are handled, the null checks are present. Not here, so it should be an issue on the Hibernate side. 

However, I'm not aware that we would set Hibernate log level to <=DEBUG for model and JS(remote server) tests, so not sure why the logging is even executed.

**Comment by mabartos** [comment]
@shawkins I've also created a PR to your fork with some changes mentioned in the upgrade guide: https://github.com/shawkins/keycloak/pull/20

There's also the new [packaging type](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.31#new-quarkus-packaging-and-maven-lifecycle) `quarkus` (instead of default `jar`) for the Quarkus modules, but we don't have to go this way right now in this PR.

We should also check the change in the size of the connection pool for Agroal/JDBC, if we're explicitly setting it to our values, or if we use the Quarkus default. The default max size increased to 50 (instead of 20). See more here: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.31#agroaljdbc

**Comment by shawkins** [comment]
@mabartos thanks for the changes. Seems good to include what you have. Our pool default max is 100, so we shouldn't have to do anything there.

**Comment by mabartos** [comment]
@shawkins Maybe we could try to set the `quarkus.log.category."org.hibernate.orm.sql.exec".level=info` for the application.properties before the bug is fixed on the Hibernate side?

**Comment by shawkins** [comment]
> However, I'm not aware that we would set Hibernate log level to <=DEBUG for model and JS(remote server) tests, so not sure why the logging is even executed.

Thankfully the JS test has passed, so we're looking at flakeyness there.

I'm not sure about debug logging yet either. It's not immediately clear what is enabling that.

> @shawkins Maybe we could try to set the `quarkus.log.category."org.hibernate.orm.sql.exec".level=info` for the application.properties before the bug is fixed on the Hibernate side?

I've pushed that in - fingers crossed that it addresses the failure.

**Comment by mabartos** [comment]
> I've pushed that in - fingers crossed that it addresses the failure.

Nope, it still thinks the DEBUG is set, and the block is executed.

**Comment by shawkins** [comment]
> Nope, it still thinks the DEBUG is set, and the block is executed.

Right, I've switched to see I can look at this locally. Definitely something in the test framework overriding the logging.

**Comment by shawkins** [comment]
@mabartos the logging issue is the same as what caused #45642 - having the quarkus boostrap runner jar in the classpath makes it seem like all levels, including trace, are enabled.

**Comment by shawkins** [comment]
@mabartos @vmuzikar the logging issues are making me think we should have a full test run somewhere with trace enabled just to see if anything else shakes out.

**Comment by shawkins** [comment]
Not exactly confidence inspiring with more runs...

@Pepo48 have you seen flakeyness with the windows service tests like this before https://github.com/keycloak/keycloak/actions/runs/21488983396/job/61906664916?pr=45612#step:5:4932

https://github.com/keycloak/keycloak/actions/runs/21488983369/job/61906538617?pr=45612 is different than #45844

Javascript tests routinely fail https://github.com/keycloak/keycloak/actions/runs/21488983410/job/61906561257?pr=45612

At least the model store tests seem better.

**Comment by Pepo48** [comment]
@shawkins no, this is actually the first time I’m seeing this, and I ran the CI repeatedly and quite extensively during last week and the beginning of this week due to the Azure PRs.

It looks like that at the time of the assertion the service is still in the process of being deleted. Do you want me to take a closer look at this?

**Comment by shawkins** [comment]
> It looks like that at the time of the assertion the service is still in the process of being deleted. Do you want me to take a closer look at this?

@Pepo48 Let's see if it keeps happening.

@vmuzikar @mabartos in general this is probably ready to merge - but it's not clear how much the upgrade is contributing to the test instability.

**Comment by vmuzikar** [comment]
The failed JS CI might be relevant. That CI seems stable in recent runs: https://github.com/keycloak/keycloak/actions/workflows/js-ci.yml

@edewit Might be able to help.

**Comment by shawkins** [comment]
> The failed JS CI might be relevant. That CI seems stable in recent runs: https://github.com/keycloak/keycloak/actions/workflows/js-ci.yml

On this pr it has failed more often than it has passed.

**Comment by edewit** [comment]
the failed javascript is due to the fact that the client isn't refreshing it's token, should be fixed now, maybe a rebase? This is the fix https://github.com/keycloak/keycloak/pull/45789

File: pom.xml [hunk 1]
```diff
@@ -1337,6 +1338,12 @@
                 <type>test-jar</type>
                 <version>${infinispan.version}</version>
             </dependency>
+            <dependency>
```
Comment (vmuzikar) [inline pom.xml:1341]: @shawkins Could you elaborate why do we need this explicit dependency now?

Comment (shawkins) [reply pom.xml:1341]: It was mentioned more explicitly in https://github.com/keycloak/keycloak/pull/44751 - we need to manage microprofile-metrics-api https://github.com/quarkusio/quarkus/pull/49735

**Review by mabartos — APPROVED** [review]
LGTM

File: pom.xml (hunk 1 above)
Comment (vmuzikar) [reply pom.xml:1341]: Thanks for the context.

**Review by vmuzikar — APPROVED** [review]
LGTM, nice work.
