### ISSUE TITLE
user list times out when current page has invalid federated users

### ISSUE THREAD

**Issue by r-buc** [keycloak/keycloak#43700]
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ldap

### Describe the bug

When using LDAP federation with "Import Users" enabled and paginating through the Admin UI user list, a page will not load successfully due excessive LDAP calls.

**Environment Details**

- LDAP Configuration:
  - Import Users: Enabled
  - Edit Mode: READ_ONLY
  - Periodic Sync: Enabled
  - Batch Size for Sync: 1000
  - "Remove invalid users during searches": Enabled
- Scenario: Several hundred users with sync conflicts due to AD user recreation (same username, different ObjectGUID/LDAP_ID)
TRACE logging enabled for `org.keycloak.storage.*`

- ca 25k users in LDAP
- ca 40k users in DB (there are obiously many stale users, the reason for this is not totally clear, maybe some mass recreation of users in LDAP or a result from Keycloak upgrade (18->26) ?)

### Version

26.2.11 (RHBK)

### Regression

- [x] The issue is a regression

### Expected behavior

The user list should maintain consistent performance across all pages.

**Fast Pages (working correctly):**
```
org.keycloak.storage.UserStorageManager TRACE This provider (JpaUserProvider) is able to return <xxxxx> users.
org.keycloak.storage.ldap.idm.store.ldap.LDAPContextManager DEBUG Creating LdapContext using properties: [...]
org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager.perf TRACE LdapOperation: lookupById... took: 2 ms
org.keycloak.storage.ldap.idm.store.ldap.LDAPIdentityStore TRACE Found ldap object and populated with the attributes. LDAP Object [...]
```
- Only individual `lookupById` operations (for validation)
- No `searchPaginated` calls
- Response time: < 2 seconds

### Actual behavior

**Slow Pages (performance issue):**
```
org.keycloak.storage.UserStorageManager TRACE This provider (JpaUserProvider) is able to return <xxxxx> users.
org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager.perf TRACE LdapOperation: searchPaginated... limit: X... took: 4 ms
org.keycloak.storage.ldap.idm.store.ldap.LDAPIdentityStore TRACE Found ldap object and populated with the attributes...
[repeated thousands of times with limit: X]
```
- Thousands of `searchPaginated` calls with a small limit X, e.g. 1
- Each call followed by X different users being populated
- Response time: several minutes (as seen from the logs, the load balancer kills the connection before finishing)

### How to Reproduce?

1. Configure LDAP federation with "Import Users" enabled
2. Delete a user in LDAP and recreate with same username (but new LDAP_ID)
3. In the Admin UI user list navigate to the page with the user

### Anything else?

**Root Cause Analysis**
(with help from deepwiki)

The issue occurs when `UserStorageManager.query()` retrieves federated users from local storage that fail LDAP validation (e.g., users recreated in AD with new ObjectGUIDs, resulting in mismatched `LDAP_ID` attributes). 

When validation returns `null` for these stale users, `UserStorageManager.query()` attempts to fill the gap by querying the LDAP provider. The `currentMax` counter is decremented for each successfully validated user, and when it reaches small values, subsequent LDAP queries use these tiny limits.
**File:** model/storage-private/src/main/java/org/keycloak/storage/UserStorageManager.java (L387-398)
```java
            // No maxResult set, we want all users
            return providersStream
                    .flatMap(provider -> pagedQuery.query(provider, currentFirst.getAndSet(0), null));
        } else {
            final AtomicInteger currentMax = new AtomicInteger(maxResults);

            // Query users with currentMax variable counting how many users we return
            return providersStream
                    .filter(provider -> currentMax.get() != 0) // If we reach currentMax == 0, we can skip querying all following providers
                    .flatMap(provider -> pagedQuery.query(provider, currentFirst.getAndSet(0), currentMax.get()))
                    .peek(userModel -> {
                        currentMax.updateAndGet(i -> i > 0 ? i - 1 : i);
```

The `paginatedSearchLDAP()` method calculates the limit based on the `maxResults` parameter passed from `UserStorageManager`:
**File:** federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPStorageProvider.java (L1107-1121)
```java

            final int limit;
            if (maxResults != null && maxResults >= 0) {
                if (firstResult != null && firstResult > 0) {
                    limit = Integer.min(ldapConfig.getBatchSizeForSync(), Integer.sum(firstResult, maxResults));
                } else {
                    limit = Integer.min(ldapConfig.getBatchSizeForSync(), maxResults);
                }
            } else {
                if (firstResult != null && firstResult > 0) {
                    limit = Integer.min(ldapConfig.getBatchSizeForSync(), firstResult);
                } else {
                    limit = ldapConfig.getBatchSizeForSync();
                }
            }
```
When combined with the `filterLocalUsers` predicate that filters out already-imported users, the stream must fetch many LDAP pages to find non-imported users.  This results in thousands of `searchPaginated()` calls with `limit=1`, each triggering an individual LDAP query.

**Proposed fix**

I guess the situation could be already improved, if the LDAP search would always use the configured batch size.

The best would be if the LDAP full sync would update the stale local users, same as when searching for a specific user.

**Comment by r-buc** [comment]
It looks like the issue is caused the setting "Remove invalid users during searches": ON. Which was the default behavior before the setting was introduced with PR #35013.

**Comment by r-buc** [comment]
removal of deleted users would probably help: #35235

**Comment by r-buc** [comment]
I think #19050 introduced at least part of the issue, as this started to fill the invalidated local users with users from LDAP one by one, which is extremely inefficient.

**Comment by r-buc** [comment]
Even with "Remove invalid users during searches": OFF, navigating to the last page of users runs the pagedQuery for the amount of users missing to create a full page.
I think LDAP providers with "Import users": ON should be excluded from the provider selection in the UserStorageManager.query() 

something like this (I guess it would be better to have  the import feature as part of the interface):
```java
                    if ((provider instanceof LdapStorageProvider) && provider.getModel().isImportEnabled()) {
                        logger.tracef("We encountered provider (%s) with import enabled, don't use it for query.", provider.getClass().getSimpleName());
                        return false;
                    }
                    if (!(provider instanceof UserCountMethodsProvider)) {
                        logger.tracef("We encountered a provider (%s) that does not implement count queries therefore we can't say how many users it can provide.", provider.getClass().getSimpleName());
                        // for this reason we need to start querying this provider and all following providers
                        droppingProviders.set(false);
                        needsAdditionalFirstResultFiltering.set(true);
                        return true; // don't filter out this provider because we are unable to say how many users it can provide
                    }
```

**Comment by pedroigor** [comment]
> I think LDAP providers with "Import users": ON should be excluded from the provider selection in the UserStorageManager.query()

As it stands today, users are imported from LDAP during searches. It is a behavior we want to revisit so that users are only imported during sync or when authenticating.

To make it a bit worse, for every federated user found, a validation will happen to check if the federated users are not stale.

The code and logic you are highlighting in this issue need a review because it does not scale well, as you are pointing out already.

I'm marking this one as a `normal` priority and moving to our backlog.

**Comment by r-buc** [comment]
@pedroigor The issue with the last page is actually a kind of separate issue and existing for a very long time. I forgot that I usually worked around it by not accessing the last page ;-)

@vramik @mhajas @mposolda  The originally described issue with "Remove invalid users during searches": ON is at least to some extend caused by #19050, specifically the paginatedSearchLDAP() in the LDAPStorageProvider, as it passes down the API pagination to the LDAP simple paging. This probably shouldn't be done at all, as its semantics are different, LDAP simple paging doesn't allow a window of results to be retrieved, it just splits the total results into pages which must be fetched one after the other.
I think paginatedSearchLDAP should therefore unconditionally `return ldapQuery.getResultList().stream();`, which uses the configured LDAP page size, which is far more efficient.

It might be a good idea to implement LDAP VLV, which fits to the pagination model and is supported by major LDAP servers, like RH DS and MS AD.
