### PR TITLE
Remove IDELauncher. Use org.keycloak.Keycloak

### LINKED ISSUE #35913: IDELauncher not working
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

IDELauncher fails to start. 
Likely introduced by #35653 

My local solution was:
Remove dependency `keycloak-quarkus-server-deployment` in `quarkus/server/pom.xml`,
which was introduced by #35653 

### Version

nightly

### Regression

- [X] The issue is a regression

### Expected behavior

IDELauncher starts successfully 

### Actual behavior

IDELauncher fails to start with:
```

Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at io.quarkus.launcher.QuarkusLauncher.launch(QuarkusLauncher.java:58)
	at io.quarkus.runtime.Quarkus.launchFromIDE(Quarkus.java:101)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:88)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at org.keycloak.quarkus._private.IDELauncher.main(IDELauncher.java:57)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.launcher.QuarkusLauncher.launch(QuarkusLauncher.java:56)
	... 4 more
Caused by: java.lang.NoClassDefFoundError: io/quarkus/bootstrap/resolver/maven/BootstrapMavenContext
	at io.quarkus.bootstrap.IDELauncherImpl.launch(IDELauncherImpl.java:85)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	... 6 more
Caused by: java.lang.ClassNotFoundException: io.quarkus.bootstrap.resolver.maven.BootstrapMavenContext
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 8 more

```

### How to Reproduce?

Try to start IDELauncher in your IDE.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by yanxch**
closes #35913

### CODE REVIEW

**Comment by yanxch** [comment]
I had problems similar to #30120 when running "Debug" in IntelliJ.

To make debug work with Java 17 I had to add the VM option: 
```
-Djava.util.logging.manager=org.jboss.logmanager.LogManager`
```
To make debug work with Java 21 I had to add the VM option:
```
-Djava.util.concurrent.ForkJoinPool.common.threadFactory=io.quarkus.bootstrap.forkjoin.QuarkusForkJoinWorkerThreadFactory
```

Added an IntelliJ run configuration with these options. Alternatively, I could add this to the README.

Feedback appreciated, thx

**Comment by yanxch** [comment]
I removed the IntelliJ run configuration from the PR again and adjusted the docs

**Review by ahus1 — APPROVED** [review]
Thank you for updating the docs and removing the file that doesn't work any more. 

I saw a positive comment by @shawkins in the parent issue, so I'm approving and merging. Let me know if I did that too eagerly.
