### ISSUE TITLE
WebAuthn stopped working in 26.2.0 but works in 26.1.5

### ISSUE THREAD

**Issue by mszpro** [keycloak/keycloak#39135]
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication/webauthn

### Describe the bug

When logging in using version tag 26.2.0 with Docker Compose, WebAuthn failed after touching the key, with such messages in log:

```
keycloak-1  | 2025-04-23 03:35:26,968 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-1) Uncaught server error: java.lang.NoSuchMethodError: 'void com.fasterxml.jackson.core.base.ParserMinimalBase.<init>(int, com.fasterxml.jackson.core.StreamReadConstraints)'
keycloak-1  | 	at com.fasterxml.jackson.dataformat.cbor.CBORParser.<init>(CBORParser.java:517)
keycloak-1  | 	at com.fasterxml.jackson.dataformat.cbor.CBORParserBootstrapper.constructParser(CBORParserBootstrapper.java:93)
keycloak-1  | 	at com.fasterxml.jackson.dataformat.cbor.CBORFactory._createParser(CBORFactory.java:427)
keycloak-1  | 	at com.fasterxml.jackson.dataformat.cbor.CBORFactory.createParser(CBORFactory.java:343)
keycloak-1  | 	at com.fasterxml.jackson.dataformat.cbor.CBORFactory.createParser(CBORFactory.java:330)
keycloak-1  | 	at com.fasterxml.jackson.dataformat.cbor.CBORFactory.createParser(CBORFactory.java:27)
keycloak-1  | 	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3907)
keycloak-1  | 	at com.webauthn4j.converter.util.CborConverter.readValue(CborConverter.java:55)
keycloak-1  | 	at org.keycloak.credential.CredentialPublicKeyConverter.convertToEntityAttribute(CredentialPublicKeyConverter.java:38)
keycloak-1  | 	at org.keycloak.credential.WebAuthnCredentialProvider.getCredentialInputFromCredentialModel(WebAuthnCredentialProvider.java:154)
keycloak-1  | 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
keycloak-1  | 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
keycloak-1  | 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
keycloak-1  | 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
keycloak-1  | 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
keycloak-1  | 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
keycloak-1  | 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
keycloak-1  | 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
keycloak-1  | 	at org.keycloak.credential.WebAuthnCredentialProvider.getWebAuthnCredentialModelList(WebAuthnCredentialProvider.java:278)
keycloak-1  | 	at org.keycloak.credential.WebAuthnCredentialProvider.isValid(WebAuthnCredentialProvider.java:188)
keycloak-1  | 	at org.keycloak.credential.UserCredentialManager.lambda$validate$11(UserCredentialManager.java:274)
keycloak-1  | 	at org.keycloak.tracing.NoopTracingProvider.trace(NoopTracingProvider.java:64)
keycloak-1  | 	at org.keycloak.tracing.NoopTracingProvider.trace(NoopTracingProvider.java:74)
keycloak-1  | 	at org.keycloak.credential.UserCredentialManager.lambda$validate$12(UserCredentialManager.java:273)
keycloak-1  | 	at java.base/java.util.Collection.removeIf(Collection.java:583)
keycloak-1  | 	at org.keycloak.credential.UserCredentialManager.validate(UserCredentialManager.java:271)
keycloak-1  | 	at org.keycloak.credential.UserCredentialManager.lambda$isValid$0(UserCredentialManager.java:77)
keycloak-1  | 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
keycloak-1  | 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
keycloak-1  | 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
keycloak-1  | 	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1787)
keycloak-1  | 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
keycloak-1  | 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
keycloak-1  | 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
keycloak-1  | 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
keycloak-1  | 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
keycloak-1  | 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
keycloak-1  | 	at org.keycloak.credential.UserCredentialManager.isValid(UserCredentialManager.java:77)
keycloak-1  | 	at org.keycloak.models.SubjectCredentialManager.isValid(SubjectCredentialManager.java:45)
keycloak-1  | 	at org.keycloak.authentication.authenticators.browser.WebAuthnAuthenticator.action(WebAuthnAuthenticator.java:233)
keycloak-1  | 	at org.keycloak.authentication.authenticators.browser.WebAuthnPasswordlessAuthenticator.action(WebAuthnPasswordlessAuthenticator.java:115)
keycloak-1  | 	at org.keycloak.authentication.DefaultAuthenticationFlow.processAction(DefaultAuthenticationFlow.java:149)
keycloak-1  | 	at org.keycloak.authentication.AuthenticationProcessor.authenticationAction(AuthenticationProcessor.java:1055)
keycloak-1  | 	at org.keycloak.services.resources.LoginActionsService.processFlow(LoginActionsService.java:378)
keycloak-1  | 	at org.keycloak.services.resources.LoginActionsService.processAuthentication(LoginActionsService.java:349)
keycloak-1  | 	at org.keycloak.services.resources.LoginActionsService.authenticate(LoginActionsService.java:341)
keycloak-1  | 	at org.keycloak.services.resources.LoginActionsService.authenticateForm(LoginActionsService.java:407)
keycloak-1  | 	at org.keycloak.services.resources.LoginActionsService$quarkusrestinvoker$authenticateForm_13d428b70e62601585246c086a52f40868a3208e.invoke(Unknown Source)
keycloak-1  | 	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
keycloak-1  | 	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
keycloak-1  | 	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
keycloak-1  | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$15.runWith(VertxCoreRecorder.java:638)
keycloak-1  | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)
keycloak-1  | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)
keycloak-1  | 	at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)
keycloak-1  | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)
keycloak-1  | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
keycloak-1  | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
keycloak-1  | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
keycloak-1  | 	at java.base/java.lang.Thread.run(Thread.java:1583)
keycloak-1  | 
```

When restoring version to 26.1.5, everything works fine.

### Version

26.2.0

### Regression

- [ ] The issue is a regression

### Expected behavior

WebAuthn to work as usual in previous versions

### Actual behavior

WebAuthn UI shows internal server error. Server log is pasted above.

### How to Reproduce?

Login with WebAuthn.

Not sure if this is related but my WebAuthn is done using Ledger with the following config:

Signature algorithms 

ES512

ES256

ES384

Relying party ID not set

Attestation conveyance preference  Not specified

Authenticator Attachment  Not specified

Require discoverable credential  Not specified

User verification requirement Not specified

Timeout Seconds

Avoid same authenticator registration Off
Acceptable AAGUIDs none
Extra Origins  none

**Comment by mszpro** [comment]
@mposolda Thanks for your detailed comment! I will try to run it outside of docker and see how it goes.
