### ISSUE TITLE
IDELauncher not working

### ISSUE THREAD

**Issue by yanxch** [keycloak/keycloak#35913]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

IDELauncher fails to start. 
Likely introduced by #35653 

My local solution was:
Remove dependency `keycloak-quarkus-server-deployment` in `quarkus/server/pom.xml`,
which was introduced by #35653 

### Version

nightly

### Regression

- [X] The issue is a regression

### Expected behavior

IDELauncher starts successfully 

### Actual behavior

IDELauncher fails to start with:
```

Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at io.quarkus.launcher.QuarkusLauncher.launch(QuarkusLauncher.java:58)
	at io.quarkus.runtime.Quarkus.launchFromIDE(Quarkus.java:101)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:88)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at org.keycloak.quarkus._private.IDELauncher.main(IDELauncher.java:57)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.launcher.QuarkusLauncher.launch(QuarkusLauncher.java:56)
	... 4 more
Caused by: java.lang.NoClassDefFoundError: io/quarkus/bootstrap/resolver/maven/BootstrapMavenContext
	at io.quarkus.bootstrap.IDELauncherImpl.launch(IDELauncherImpl.java:85)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	... 6 more
Caused by: java.lang.ClassNotFoundException: io.quarkus.bootstrap.resolver.maven.BootstrapMavenContext
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 8 more

```

### How to Reproduce?

Try to start IDELauncher in your IDE.

**Comment by pedroigor** [comment]
@vramik @shawkins As I mentioned before, we don't need this class anymore but use the `Keycloak` Java application from the `keycloak-junit5` module.

The `Keycloak` application is what we use in our testsuite as well as in the new test framework. Keeping both is redundant.

Can we remove it from our codebase?

**Comment by vramik** [comment]
@pedroigor personally I've never used the `IDELauncher`, instead I use the `Keycloak` Java application from the `keycloak-junit5` module as you mentioned above.

**Comment by shawkins** [comment]
> Can we remove it from our codebase?

I'm good with removal as well. For continuity maybe it could default to start-dev as well.

**Comment by yanxch** [comment]
Shall I prepare a PR?

**Comment by shawkins** [comment]
> Shall I prepare a PR?

@yanxch Yes if you have the time. It looks like the pom and the README will need updates as well.

**Comment by yanxch** [comment]
@shawkins Sorry to bother you but I'm stuck.
How do you start the server in debug mode with the `Keycloak` class?

I use `start-dev` as CLI argument in Intellij Run Configuration.

But as soon as I try to add `--debug` it fails with:
```
Unknown option: '--debug'
Try 'kc.sh start-dev --help' for more information on the available options.
```

And when I try to start "Debug" with just `start-dev` the process kind of freezes.

Thx

**Comment by shawkins** [comment]
> But as soon as I try to add --debug it fails with

--debug is currently supported in the calling kc.sh and kc.bat files - these have to be translated to process arguments, not handled as program arguments by keycloak.

> And when I try to run "Debug" in IntelliJ with just start-dev the process kind of freezes.

It seemed to work for me with Eclipse. @pedroigor what IDE do you use?

**Comment by yanxch** [comment]
I'm taking baby steps here but nevertheless some progress.
I figured out I'm blind due to this message I was not honoring enough until now when I start with "Debug":
```
ERROR: The LogManager accessed before the "java.util.logging.manager" system property was set to "org.jboss.logmanager.LogManager". Results may be unexpected.
```

Then the system doesn't boot up correctly. 
Still have to find out what is happening.

**Comment by yanxch** [comment]
Sorry for the spam. Just to document my failures so it may help others in the future.

I had to add the VM option `-Djava.util.logging.manager=org.jboss.logmanager.LogManager` - then debugging `Keycloak` in IntelliJ is working

**Comment by vramik** [comment]
@yanxch thanks, personally I use Netbeans, so I cannot verify it, but AFAIK @pedroigor does use InjtelliJ.

**Comment by yanxch** [comment]
Should we keep this open? At least for me, `IDELauncher` is working again in current `main`

**Comment by shawkins** [comment]
> Should we keep this open? At least for me, IDELauncher is working again in current main

Having a single mechanism would be best moving forward. Is your pr ready to move out of a draft state?
