### ISSUE TITLE
Remove dependencies on Resteasy API and rely on JAX-RS API as much as possible

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#15374]
### Description

Our JAX-RS code is relying on the Resteasy API. Some of the code even rely on Resteasy internals.

Being a JAX-RS application, Keycloak should favor as much as possible using the JAX-RS API and, where not possible, provide a layer of indirection to avoid direct dependencies on the underlying JAX-RS implementation.

After an initial investigation, the following work should be done to change our code to be full JAX-RS compliant:

* Avoid direct usage of contextual objects from Resteasy such as `HttpRequest`, `HttpResponse`, and `HttpHeaders`.
* Avoid programmatic context injection by removing code relying on `ResteasyProviderFactory#injectProperties`

### Motivation

If we want to become completely agnostic about the underlying stack we should favor using standard APIs.

### Details

This task is important to move to Resteasy Reactive.

**Comment by thomasdarimont** [comment]
Would it be save to use `javax.ws.rs.container.ResourceContext#initResource` instead of `ResteasyProviderFactory#injectProperties`?

**Comment by thomasdarimont** [comment]
A lot of user code currently relies on types like `org.jboss.resteasy.spi.HttpRequest` obtained via Keycloak API like `org.keycloak.authentication.RequiredActionContext#getHttpRequest`.

I think it is important to have a good migration story here, e.g. by producing an intermediate major release with the Keycloak API methods deprecated which use resteasy types with some clear deprecation notes and migration advice.
Otherwise, it will IMHO be quite difficult for users to upgrade to the new version, since it would require a lot of changes to user extension code.

**Comment by lmorocz** [comment]
Hi @pedroigor !

This change sadly breaks runtime backward compatibility with custom FormActions using org.keycloak.authentication.FormContext#getHttpRequest and such. 

We have a custom RegistrationValidationFormAction implementation compiled with org.keycloak.bom:keycloak-spi-bom **19.0.1** version. After we upgraded our Keycloak instance from 20.0.5 to 21.0.0 the custom action throws the following error:
```
2023-03-03 10:58:16,393 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-50) Uncaught server error: java.lang.NoSuchMethodError: 'org.jboss.resteasy.spi.HttpRequest org.keycloak.authentication.ValidationContext.getHttpRequest()'
        at <redacted>.RegistrationValidationFormAction.validate(<redacted>RegistrationValidationFormAction.java:64)
        at org.keycloak.authentication.FormAuthenticationFlow.processAction(FormAuthenticationFlow.java:215)
        at org.keycloak.authentication.DefaultAuthenticationFlow.processAction(DefaultAuthenticationFlow.java:133)
        at org.keycloak.authentication.AuthenticationProcessor.authenticationAction(AuthenticationProcessor.java:985)
        at org.keycloak.services.resources.LoginActionsService.processFlow(LoginActionsService.java:323)
        at org.keycloak.services.resources.LoginActionsService.processRegistration(LoginActionsService.java:667)
        at org.keycloak.services.resources.LoginActionsService.registerRequest(LoginActionsService.java:723)
        at org.keycloak.services.resources.LoginActionsService.processRegister(LoginActionsService.java:701)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
        at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:84)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:71)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
        at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:430)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:408)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
        at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
        at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
``` 

Before v21 the org.keycloak.authentication.FormContext#getHttpRequest returned org.jboss.resteasy.spi.HttpRequest but now it returns the new org.keycloak.http.HttpRequest and the wrapper HttpRequestImpl implementation.

We **have to rebuild** our maven project with org.keycloak.bom:keycloak-spi-bom 21.0.0 dependency and install this artifact to v21 Keycloak instances.

This is a runtime error so it is not trivial for first sight and may takes a long time to occur in test/production. So IMHO this should be in the upgrade docs as a warning.

**Comment by raphael-beck** [comment]
Hello,
This enhancement has broken our plugin implementation and we might be blocked on Keycloak v20 the time we found a workaround.
@pedroigor You mentioned a migration guide, could you provide the link to it please?
Thank you
