### ISSUE TITLE
NoClassDefFoundError after upgrading from 18.x.x to 19.0.1

### ISSUE THREAD

**Issue by lstoeferle** [keycloak/keycloak#13719]
### Describe the bug

After upgrading `org.keycloak:keycloak-core` from `v18.0.2` to `v19.0.1` in a Spring Boot WebFlux project the `org.springframework.security.web.server.authentication.AuthenticationWebFilter` refuses to initialise due to this error (using Gradle 7.5.1):

```
java.lang.NoClassDefFoundError: org/jboss/logging/Logger
	at app//org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.resolveMethodArguments(AutowiredAnnotationBeanPostProcessor.java:767)
	at app//org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.inject(AutowiredAnnotationBeanPostProcessor.java:719)
	at app//org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
	at app//org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
	at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)
	at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
	at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at app//org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at app//org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at app//org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at app//org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at app//org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
	at app//org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at app//org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at app//org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734)
	at app//org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
	at app//org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at app//org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:132)
	at app//org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
	at app//org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124)
	... 137 more
```

### Version

19.0.1

### Expected behavior

`AuthenticationWebFilter` initialisation should work without installing additional dependencies explicitly

### Actual behavior

`AuthenticationWebFilter` fails to initialise

### How to Reproduce?

Create a Spring Boot WebFlux project with an `org.springframework.security.web.server.authentication.AuthenticationWebFilter` which using `org.keycloak:keycloak-core` functionality.

**Comment by Benesss** [comment]
Seems to be similar to https://github.com/keycloak/keycloak/issues/13954
I'm also facing a similar issue with Keycloak 19.0.1-legacy

**Comment by mposolda** [comment]
Adding to backlog as spring adapter has very low priority and Keycloak team won't be able to look at this in the near future. Anyone is welcome to look at it (after confirm that this is Keycloak bug and not incorrect usage etc) and eventually send PR with the fix.

**Comment by stianst** [comment]
Spring adapters have been deprecated for a long time, and will be removed in Keycloak 25. For more information look at https://www.keycloak.org/2024/03/keycloak-2400-released.html.
