### ISSUE TITLE
Experimental workflow plugin does not work after upgrade

### ISSUE THREAD

**Issue by spictera** [keycloak/keycloak#48403]
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

workflows

### Describe the bug

The workflow plugin code does not work after upgrading from Keycloak 26.2.5 to 26.4.5
It is not possible to create any new config.

### Version

26.4.5

### Regression

- [x] The issue is a regression

### Expected behavior

Create new workflow should work.

### Actual behavior

The "create new workflow" returns error in keycloak that Jacskon function is not existing anymore.

"event.sequence": 19453, "log.logger": "org.keycloak.services.error.KeycloakErrorHandler", "log.level": "ERROR", "message": "Uncaught server error", "process.thread.name": "executor-thread-24", "process.thread.id": 24547, "mdc": {}, "ndc": "", "host.hostname": "janus.saabgroup.com", "process.name": "/usr/lib/jvm/java-21-openjdk-21.0.9.0.10-1.el9.x86_64/bin/java", "process.pid": 1, "exception": { "refId": 1, "exceptionType": "java.lang.NoSuchMethodError", "error.message": "'java.util.Set com.fasterxml.jackson.databind.JsonNode.properties()'", "frames": [ { "class": "org.keycloak.representations.workflows.MultivaluedHashMapValueDeserializer", "method": "deserialize", "line": 20 }, { "class": "com.fasterxml.jackson.databind.deser.impl.MethodProperty", "method": "deserializeAndSet", "line": 129 }, { "class": "com.fasterxml.jackson.databind.deser.BeanDeserializer", "method": "vanillaDeserialize", "line": 314 }, { "class": "com.fasterxml.jackson.databind.deser.BeanDeserializer", "method": "deserialize", "line": 177 }, { "class": "com.fasterxml.jackson.databind.deser.std.CollectionDeserializer", "method": "_deserializeFromArray", "line": 355 }, { "class": "com.fasterxml.jackson.databind.deser.std.CollectionDeserializer", "method": "deserialize", "line": 244 }, { "class": "com.fasterxml.jackson.databind.deser.std.CollectionDeserializer", "method": "deserialize", "line": 28 }, { "class": "com.fasterxml.jackson.databind.deser.impl.MethodProperty", "method": "deserializeAndSet", "line": 129 }, { "class": "com.fasterxml.jackson.databind.deser.BeanDeserializer", "method": "vanillaDeserialize", "line": 314 }, { "class": "com.fasterxml.jackson.databind.deser.BeanDeserializer", "method": "deserialize", "line": 177 }, { "class": "com.fasterxml.jackson.databind.deser.DefaultDeserializationContext", "method": "readRootValue", "line": 323 }, { "class": "com.fasterxml.jackson.databind.ObjectReader", "method": "_bindAndClose", "line": 2051 }, { "class": "com.fasterxml.jackson.databind.ObjectReader", "method": "readValue", "line": 1427 }, { "class": "io.quarkus.resteasy.reactive.jackson.runtime.serialisers.ServerJacksonMessageBodyReader", "method": "doReadFrom", "line": 93 }, { "class": "io.quarkus.resteasy.reactive.jackson.runtime.serialisers.ServerJacksonMessageBodyReader", "method": "readFrom", "line": 44 }, { "class": "io.quarkus.resteasy.reactive.jackson.runtime.serialisers.ServerJacksonMessageBodyReader", "method": "readFrom", "line": 83 }, { "class": "io.quarkus.resteasy.reactive.jackson.runtime.serialisers.ServerJacksonMessageBodyReader_ClientProxy", "method": "readFrom" }, { "class": "org.jboss.resteasy.reactive.server.handlers.RequestDeserializeHandler", "method": "readFrom", "line": 126 }, { "class": "org.jboss.resteasy.reactive.server.handlers.RequestDeserializeHandler", "method": "handle", "line": 84 }, { "class": "io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext", "method": "invokeHandler", "line": 177 }, { "class": "org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext", "method": "run", "line": 147 }, { "class": "io.quarkus.vertx.core.runtime.VertxCoreRecorder$15", "method": "runWith", "line": 645 }, { "class": "org.jboss.threads.EnhancedQueueExecutor$Task", "method": "doRunWith", "line": 2651 }, { "class": "org.jboss.threads.EnhancedQueueExecutor$Task", "method": "run", "line": 2630 }, { "class": "org.jboss.threads.EnhancedQueueExecutor", "method": "runThreadBody", "line": 1622 }, { "class": "org.jboss.threads.EnhancedQueueExecutor$ThreadBody", "method": "run", "line": 1589 }, { "class": "org.jboss.threads.DelegatingRunnable", "method": "run", "line": 11 }, { "class": "org.jboss.threads.ThreadLocalResettingRunnable", "method": "run", "line": 11 }, { "class": "io.netty.util.concurrent.FastThreadLocalRunnable", "method": "run", "line": 30 }, { "class": "java.lang.Thread", "method": "run", "line": 1583 } ]

### How to Reproduce?

Try creating a new workflow

### Anything else?

Besides this, there is no "Edit" or "View" for this.

**Comment by pedroigor** [comment]
@spictera Thanks for trying it out. We appreciate feedback when a feature is in an experimental state.

In the latest release, Workflows is now fully supported, and I would recommend trying out the latest version.

**Comment by spictera** [comment]
> @spictera Thanks for trying it out. We appreciate feedback when a feature is in an experimental state.
> 
> In the latest release, Workflows is now fully supported, and I would recommend trying out the latest version. 

Can you please be more precise of from which version workflow is supported?
I used it on 26.2.5 where it worked, upgraded to 26.4.5 where it stoped working due to json parsing changes.

**Comment by sguilhen** [comment]
You will need to upgrade to Keycloak 26.6.x
