### ISSUE TITLE
Impossible to update client settings after previously updated client in tab "Advanced"

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#38500]
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

- Login to admin console
- Go to *Clients* and create client `foo`
- Go to tab *Advanced* of the client and scroll down to the bottom of *Fine grain OpenID Connect configuration* and click the button *Save*. There is message *Client is successfully updated*
- Go back to tab *Settings* and try to update some client settings. For example disable *Standard flow* for the client
- Click *Save* . It is not possible to save the client and there is error in the javascript console:

```
Uncaught (in promise) TypeError: bt.attributes['acr.loa.map'].filter is not a function
    Le ClientDetails.tsx:368
    save ClientDetails.tsx:453
    onClick FixedButtonGroup.tsx:34
```

NOTE: After going entirely back from the client to the client itself and then click to client `foo` again, I am able to disable token exchange. In the end, it is possible to achieve everything, but user-experience is not so great...

### Version

nightly (from 2025-03-27)

### Regression

- [x] The issue is a regression

### Expected behavior

Possible to update client in the tab *Settings* after previously updated the client in the tab *Advanced*

### Actual behavior

Not possible to update client in the tab *Settings* after previously updated the client in the tab *Advanced*

### How to Reproduce?

See above

### Anything else?

I've tried with Keycloak 26.1.0 and things work as expected. So looks like a regression...

**Comment by graziang** [comment]
It doesn't seem related to #36441, as it doesn't modify the "acr.loa.map" client attributes in any way. It looks more related to some UI changes in the parsing of "acr.loa.map" that may have been introduced after #33205, which actually works in 26.1, but I could be wrong.

**Comment by ssilvert** [comment]
I'm not considering this to be a regression right now.  I think this bug has been here for several years.  Also, there is a simple workaround so I don't consider it a blocker.  The workaround is just to go all the way out to the client list and go in again to edit details.

Hopefully, [my proposed fix](https://github.com/keycloak/keycloak/pull/38669) is correct.
