### ISSUE TITLE
Keycloak server not working on JDK 11.0.15

### ISSUE THREAD

**Issue by rgala** [keycloak/keycloak#11652]
### Describe the bug

After upgrading Java to 11.0.15, Keycloak fails with an error on first HTTP request sent to the server:

> 15:40:40,553 ERROR [io.undertow.request] (default task-1) UT005071: Undertow request failed HttpServerExchange{ GET /auth/}: java.lang.NoClassDefFoundError: Could not initialize class org.xnio.conduits.Conduits
> 	at io.undertow.core@2.2.14.Final//io.undertow.conduits.AbstractFixedLengthStreamSinkConduit.writeFinal(AbstractFixedLengthStreamSinkConduit.java:175)
> 	at org.jboss.xnio@3.8.5.Final//org.xnio.conduits.ConduitStreamSinkChannel.writeFinal(ConduitStreamSinkChannel.java:104)
> 	at io.undertow.core@2.2.14.Final//io.undertow.channels.DetachableStreamSinkChannel.writeFinal(DetachableStreamSinkChannel.java:195)
> 	at io.undertow.core@2.2.14.Final//io.undertow.server.HttpServerExchange$WriteDispatchChannel.writeFinal(HttpServerExchange.java:2171)
> 	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.spec.ServletOutputStreamImpl.writeBufferBlocking(ServletOutputStreamImpl.java:582)
> 	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.spec.ServletOutputStreamImpl.close(ServletOutputStreamImpl.java:619)
> 	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.spec.HttpServletResponseImpl.closeStreamAndWriter(HttpServletResponseImpl.java:498)
> 	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.spec.HttpServletResponseImpl.responseDone(HttpServletResponseImpl.java:587)
> 	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:334)
> 	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79)
> 	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134)
> 	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131)
> 	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
> 	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
> 	at org.wildfly.extension.undertow@26.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1544)
> 	at org.wildfly.extension.undertow@26.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1544)
> 	at org.wildfly.extension.undertow@26.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1544)
> 	at org.wildfly.extension.undertow@26.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1544)
> 	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:255)
> 	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79)
> 	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100)
> 	at io.undertow.core@2.2.14.Final//io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)
> 	at io.undertow.core@2.2.14.Final//io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852)
> 	at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
> 	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
> 	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
> 	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
> 	at org.jboss.xnio@3.8.5.Final//org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280)
> 	at java.base/java.lang.Thread.run(Thread.java:834)

Tried versions 17.0.0, 17.0.1 and 18.0.0.

### Version

17.0.0

### How to Reproduce?

Upgrade Java to 11.0.15

**Comment by andreaTP** [comment]
Hi @rgala , thanks for this report!
Would you mind testing your setup with JDK 11.0.14?
Also, would you mind sharing more details about what you are running as a few steps to reproduce the issue?

I do suspect that this can be related to: #11675

**Comment by rgala** [comment]
Hello.

On 11.0.14 it works without problems.

Reproducing is easy, just start the server by executing standalone.bat/standalone.sh script and then open the admin panel.

**Comment by andreaTP** [comment]
@rgala thanks for the feedback!
Interesting to know that we have problems on the WildFliy distribution side as well.

**Comment by psytester** [comment]
I did not catch your error while normal user login nor usage of admin panel.
But due to your WildFly ticket, it looks like a Windows specific issue in (Oracle) JDK because of https://bugs.openjdk.java.net/browse/JDK-8285445

My setup is different: No Windows, but Linux (RHEL 8.5) and OpenJDK 11.0.15+9-LTS

**Comment by cosmedin** [comment]
I've come across this problem with Spring too. Solved by using jdk 11.0.14.
Thx.
