### ISSUE TITLE
Cannot find type definition file for 'cypress'

### ISSUE THREAD

**Issue by mfrances17** [keycloak/keycloak#18811]
After rebasing to latest code, I'm getting this error in VS Code:

tsconfig.json
Cannot find type definition file for 'cypress' ts [1,1]

Looking at the diff, it is most likely related to https://github.com/keycloak/keycloak-admin-ui/pull/336 when jest and cypress types were introduced at the bottom of the json file.
