### ISSUE TITLE
Pinned Helm extension versions in operator/pom.xml conflict with BOM

### ISSUE THREAD

**Issue by Pepo48** [keycloak/keycloak#52044]
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

The `quarkus-helm` and `quarkus-operator-sdk-helm` dependencies in `operator/pom.xml` use explicitly pinned versions (`1.2.7` and `7.4.0`) that conflict with the BOM-managed `quarkus-operator-sdk` version. This causes an intermittent `NoClassDefFoundError` for `AdditionalHelmCRDBuildItem` during Quarkus augmentation in operator tests.

The failure is intermittent because Quarkus bootstrap version resolution between the explicit `7.4.0` and the conditionally-injected `7.8.0` deployment module is non-deterministic.

This was introduced in #42079. @KyriosGN0, was there a specific reason for pinning these versions rather than letting the `io.quarkus.platform:quarkus-operator-sdk-bom` manage them? The BOM already manages `quarkus-helm` at `1.4.1`, and `quarkus-operator-sdk-helm` is auto-injected via the conditional dependency mechanism in `quarkus-operator-sdk`.

### Version

nightly (quarkus-next)

### Regression

- [ ] The issue is a regression

### Expected behavior

Operator tests (`WatchedResourcesTest`, etc.) should pass consistently.

### Actual behavior

The "Test remote (slow)" job intermittently fails with:

`NoClassDefFoundError: io/quarkiverse/helm/spi/AdditionalHelmCRDBuildItem`

Examples of ccurrences since the Helm chart PR was merged on Aug 12:
- https://github.com/keycloak/keycloak/actions/runs/32608380879 (quarkus-next)
- https://github.com/keycloak/keycloak/actions/runs/32818878299 (main)

### Anything else?

**Comment by KyriosGN0** [comment]
@Pepo48 Yes, we needed specific version in order to avoid bugs in newer versions

**Comment by Pepo48** [comment]
@KyriosGN0 then I would suggest bumping at least `quarkus-helm` from `1.2.7` to `1.4.1` to avoid the conflict. That said, this is just a temporary workaround, a similar issue can happen again if a future QOSDK version introduces new SPI classes.

Our best practice in the operator module is to let the `io.quarkus.platform:quarkus-operator-sdk-bom` manage extension versions (as we do for `quarkus-operator-sdk`, `quarkus-operator-sdk-bundle-generator`, etc.). Alternatively, the conditional injection could be suppressed by adding a Maven exclusion for `quarkus-operator-sdk-helm` on the `quarkus-operator-sdk` dependency, but that's fragile and defeats the purpose of the conditional dependency mechanism.

cc: @vmuzikar @shawkins

**Comment by shawkins** [comment]
@Pepo48 did you see https://github.com/keycloak/keycloak/pull/51948

**Comment by Pepo48** [comment]
Also I just noticed that this was already reported by @michalvavrik: https://github.com/keycloak/keycloak/issues/51943

I'm sorry Michal for stepping on your toes. Feel free to close this one in favour of yours.

**Comment by Pepo48** [comment]
> [@Pepo48](https://github.com/Pepo48) did you see [#51948](https://github.com/keycloak/keycloak/pull/51948)

I spotted it too late, sorry for that again. Closing this as a duplicate.

**Comment by michalvavrik** [comment]
> [@Pepo48](https://github.com/Pepo48) Yes, we needed specific version in order to avoid bugs in newer versions

we bumped Quarkus platform, now managed version of QOSDK is 7.8.0 which contains the fix. I think @Pepo48 solution is right, but we shall ping you in Peter's PR so that you can double-check (though we may not wait if you are busy these days because this bug is bit annoying when building Keycloak). Thanks for swift answer.
