### ISSUE TITLE
KeycloakLogger does not work with liquibase 4.11.x

### ISSUE THREAD

**Issue by jmax01** [keycloak/keycloak#12449]
### Describe the bug

Upgrading liquibase to 4.11.x (to address CVEs) causes keycloak to fail as `org.keycloak.connections.jpa.updater.liquibase.log.KeycloakLogger` 
uses `liquibase.logging.core.DefaultLogMessageFilter` which has been removed: 
https://github.com/liquibase/liquibase/commit/d051cc08a02f401b367077f9f031225d71040a43

```
Caused by: java.lang.NoClassDefFoundError: liquibase/logging/core/DefaultLogMessageFilter
	at org.keycloak.connections.jpa.updater.liquibase.log.KeycloakLogger.<init>(KeycloakLogger.java:36)
	at org.keycloak.connections.jpa.updater.liquibase.log.KeycloakLogService.getLog(KeycloakLogService.java:37)
	at liquibase.Scope.getLog(Scope.java:338)
	at liquibase.servicelocator.StandardServiceLocator.findInstances(StandardServiceLocator.java:20)
	at liquibase.Scope.getCurrentScope(Scope.java:93)
	at org.keycloak.connections.jpa.updater.liquibase.conn.DefaultLiquibaseConnectionProvider.baseLiquibaseInitialization(DefaultLiquibaseConnectionProvider.java:75)
	at org.keycloak.connections.jpa.updater.liquibase.conn.DefaultLiquibaseConnectionProvider.create(DefaultLiquibaseConnectionProvider.java:62)
	at org.keycloak.connections.jpa.updater.liquibase.conn.DefaultLiquibaseConnectionProvider.create(DefaultLiquibaseConnectionProvider.java:44)
	at org.keycloak.services.DefaultKeycloakSession.getProvider(DefaultKeycloakSession.java:316)
	at org.keycloak.connections.jpa.updater.liquibase.lock.LiquibaseDBLockProvider.lazyInit(LiquibaseDBLockProvider.java:62)
	at org.keycloak.connections.jpa.updater.liquibase.lock.LiquibaseDBLockProvider.lambda$waitForLock$2(LiquibaseDBLockProvider.java:96)
	at org.keycloak.models.utils.KeycloakModelUtils.suspendJtaTransaction(KeycloakModelUtils.java:756)
	at org.keycloak.connections.jpa.updater.liquibase.lock.LiquibaseDBLockProvider.waitForLock(LiquibaseDBLockProvider.java:94)
	at org.keycloak.services.resources.KeycloakApplication$1.run(KeycloakApplication.java:136)
	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:242)
	at org.keycloak.services.resources.KeycloakApplication.startup(KeycloakApplication.java:130)
	
Caused by: java.lang.ClassNotFoundException: liquibase.logging.core.DefaultLogMessageFilter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
```

### Version

18.0.0

### Expected behavior

Should start

### Actual behavior

```
Caused by: java.lang.NoClassDefFoundError: liquibase/logging/core/DefaultLogMessageFilter
	at org.keycloak.connections.jpa.updater.liquibase.log.KeycloakLogger.<init>(KeycloakLogger.java:36)
	at org.keycloak.connections.jpa.updater.liquibase.log.KeycloakLogService.getLog(KeycloakLogService.java:37)
	at liquibase.Scope.getLog(Scope.java:338)
	at liquibase.servicelocator.StandardServiceLocator.findInstances(StandardServiceLocator.java:20)
	at liquibase.Scope.getCurrentScope(Scope.java:93)
	at org.keycloak.connections.jpa.updater.liquibase.conn.DefaultLiquibaseConnectionProvider.baseLiquibaseInitialization(DefaultLiquibaseConnectionProvider.java:75)
	at org.keycloak.connections.jpa.updater.liquibase.conn.DefaultLiquibaseConnectionProvider.create(DefaultLiquibaseConnectionProvider.java:62)
	at org.keycloak.connections.jpa.updater.liquibase.conn.DefaultLiquibaseConnectionProvider.create(DefaultLiquibaseConnectionProvider.java:44)
	at org.keycloak.services.DefaultKeycloakSession.getProvider(DefaultKeycloakSession.java:316)
	at org.keycloak.connections.jpa.updater.liquibase.lock.LiquibaseDBLockProvider.lazyInit(LiquibaseDBLockProvider.java:62)
	at org.keycloak.connections.jpa.updater.liquibase.lock.LiquibaseDBLockProvider.lambda$waitForLock$2(LiquibaseDBLockProvider.java:96)
	at org.keycloak.models.utils.KeycloakModelUtils.suspendJtaTransaction(KeycloakModelUtils.java:756)
	at org.keycloak.connections.jpa.updater.liquibase.lock.LiquibaseDBLockProvider.waitForLock(LiquibaseDBLockProvider.java:94)
	at org.keycloak.services.resources.KeycloakApplication$1.run(KeycloakApplication.java:136)
	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:242)
	at org.keycloak.services.resources.KeycloakApplication.startup(KeycloakApplication.java:130)
	
Caused by: java.lang.ClassNotFoundException: liquibase.logging.core.DefaultLogMessageFilter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
```

### How to Reproduce?

Upgrade liquibase to 4.11.x

**Comment by sguilhen** [comment]
Liquibase upgrade due to CVEs and quarkus alignment, will be tracked in https://github.com/keycloak/keycloak/issues/15089.
