### PR TITLE
Fix POST /admin/realms/{realm}/clients-initial-access returning HTTP 200 instead of 201

### LINKED ISSUE #49185: HttpResponse.setStatus is not generally usable
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

_No response_

### Describe the bug

While HttpResponse.set/getStatus have a localized affect, the value set is overwritten by any unhandled exception, and ultimately by the JAX-RS response logic - that is if a Response is returned, that will have the code used, void will use the no content code, and serialized values will use 200.

This also means that the current return value for the clients-initial-access is incorrect - https://github.com/keycloak/keycloak/blob/a1405663f73952a4a30a9999bbea537010c5d89c/services/src/main/java/org/keycloak/services/resources/admin/ClientInitialAccessResource.java#L111

### Version

26 and earlier

### Regression

- [ ] The issue is a regression

### Expected behavior

javadocs for get/setStatus need added, or the methods should be deprecated.

### Actual behavior

Usage of these methods can lead to the wrong status code.

### How to Reproduce?

Observe that clients-initial-access actually returns 200, not 201.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ThreeMangoTrees**
## Summary

- `POST /admin/realms/{realm}/clients-initial-access` was returning HTTP 200 instead of 201 as required by the spec
- Root cause: `HttpResponse.setStatus()` is silently overwritten by the JAX-RS runtime whenever a resource method returns a plain object — only a `Response` return type carries the status code through
- Fix: change `ClientInitialAccessResource.create()` to return `Response.status(201).entity(rep).location(uri).build()` using the proper JAX-RS pattern
- Update admin client `ClientInitialAccessResource.create()` return type from `ClientInitialAccessPresentation` to `Response` so callers can inspect the HTTP status and `Location` header
- Fix all affected test callers to use `readEntity(ClientInitialAccessPresentation.class)` for correct client-side deserialization

## Changes

- `services/src/main/java/org/keycloak/services/resources/admin/ClientInitialAccessResource.java` — core fix
- `integration/admin-client/src/main/java/org/keycloak/admin/client/resource/ClientInitialAccessResource.java` — return type change
- `tests/base/src/test/java/org/keycloak/tests/admin/InitialAccessTokenResourceTest.java` — assert 201 and Location header
- `testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/client/InitialAccessTokenTest.java` — use `readEntity()`
- Several other test files updated to use `readEntity()` after the interface change

## Why Local Reproduction Was Not Possible

The fix for issue #49185 (POST /admin/realms/{realm}/clients-initial-access returning HTTP 200
instead of 201) could not be verified locally by starting a patched Keycloak server. There were
three compounding reasons.

### Pre-existing compilation errors in the main branch

Three modules in the current main branch fail to compile. These failures are unrelated to the
fix for #49185 and were introduced by other contributors in the days preceding this fix.

  - model/infinispan: JGroupsConfigurator.java fails because JpaConnectionProvider does not
    satisfy a generic type bound during compilation. Introduced by commit 23bac7b976 on May 20.

  - model/storage-services: UserStorageProviderResource.java has a similar type resolution
    failure where LDAPStorageMapper cannot be verified to satisfy <T extends Provider>, and
    RealmModel cannot be found by the compiler.

  - rest/admin-v2: Multiple files reference symbols (AdminAuth, AdminEventBuilder,
    AdminPermissionEvaluator) that no longer exist in the packages they expect.

Because these modules are in the transitive dependency chain of quarkus/runtime and
quarkus/dist (the modules that produce the runnable server), a full build of Keycloak
cannot complete.

### The only available distribution is from April 22 and is stale

Rather than building from scratch, patching the pre-built distribution at
`quarkus/dist/target/keycloak-999.0.0-SNAPSHOT/` was attempted. However, that distribution is
approximately four weeks old. Many classes were added to the source since April 22 that are
absent from its JARs. The first missing class encountered at server startup was:

  `org.keycloak.representations.idm.oid4vc.UserVerifiableCredentialRepresentation`

This caused a `ClassNotFoundException` that prevented the server from starting.

### Patching individual class files into the Quarkus uber-JAR causes classloader conflicts

Quarkus bundles all application classes into a single uber-JAR at lib/app/keycloak.jar.
The Quarkus augmentation/deployment code (run by kc.sh build) was compiled against the
April 22 versions of all Keycloak classes and baked into the distribution.

When newer class files were injected into `keycloak.jar` to resolve the `ClassNotFoundException`,
the old deployment code and the new application code held conflicting versions of the same
class (e.g. `org.keycloak.representations.userprofile.config.UPConfig`). This caused a
LinkageError during kc.sh build:

  loader constraint violation: loader QuarkusClassLoader wants to load class UPConfig.
  A different class with the same name was previously loaded by URLClassLoader.

There is no clean way to partially patch an existing Quarkus distribution — the entire
distribution must be rebuilt as a coherent unit from the same source snapshot.

## Test plan

- [ ] `InitialAccessTokenResourceTest.testInitialAccessTokens()` asserts HTTP 201 and a non-null `Location` header
- [ ] `InitialAccessTokenResourceTest.testPeriodicExpiration()` uses `readEntity()` correctly
- [ ] `InitialAccessTokenTest` (Arquillian) updated to use `readEntity()`
- [ ] Existing behaviour (token content, expiration, count) unchanged

Fixes #49185

### CODE REVIEW

File: integration/admin-client/src/main/java/org/keycloak/admin/client/resource/ClientInitialAccessResource.java [hunk 1]
```diff
@@ -39,7 +40,7 @@ public interface ClientInitialAccessResource {
     @POST
     @Consumes(MediaType.APPLICATION_JSON)
     @Produces(MediaType.APPLICATION_JSON)
-    ClientInitialAccessPresentation create(ClientInitialAccessCreatePresentation rep);
+    Response create(ClientInitialAccessCreatePresentation rep);
```
Comment (michalvavrik) [inline integration/admin-client/src/main/java/org/keycloak/admin/client/resource/ClientInitialAccessResource.java]: this is not necessary, Quarkus REST uses `instanceof` under the hood

File: services/src/main/java/org/keycloak/services/resources/admin/ClientInitialAccessResource.java [hunk 2]
```diff
@@ -83,7 +81,7 @@ public ClientInitialAccessResource(KeycloakSession session, AdminPermissionEvalu
     @Tag(name = KeycloakOpenAPI.Admin.Tags.CLIENT_INITIAL_ACCESS)
     @Operation( summary = "Create a new initial access token.")
     @APIResponse(responseCode = "201", description = "Created", content = @Content(schema = @Schema(implementation = ClientInitialAccessCreatePresentation.class)))
-    public Object create(ClientInitialAccessCreatePresentation config) {
+    public Response create(ClientInitialAccessCreatePresentation config) {
```
Comment (michalvavrik) [inline services/src/main/java/org/keycloak/services/resources/admin/ClientInitialAccessResource.java:84]: this is not necessary

**Review by michalvavrik — CHANGES_REQUESTED** [review]
Thank you. Let's try to limit level of changes to only necessary ones and let's test your changes locally before you push them. I think description of this PR why is it not possible is not precise.

File: integration/admin-client/src/main/java/org/keycloak/admin/client/resource/ClientInitialAccessResource.java (hunk 1 above)
Comment (shawkins) [reply integration/admin-client/src/main/java/org/keycloak/admin/client/resource/ClientInitialAccessResource.java]: It's also breaking as this interface is part of the java client. This change, and all of the test logic updates should be removed.

Either introduce a seperate method, e.g.

```
Response doCreate(ClientInitialAccessCreatePresentation rep);
```

Or test the server side change with a rest call not via the java client.

File: services/src/main/java/org/keycloak/services/resources/admin/ClientInitialAccessResource.java (hunk 2 above)
Comment (ThreeMangoTrees) [reply services/src/main/java/org/keycloak/services/resources/admin/ClientInitialAccessResource.java:84]: @michalvavrik  Just curious, if the `create` method only returns `Response` type, why should the return type of the method  still be `Object` ?

Comment (michalvavrik) [reply services/src/main/java/org/keycloak/services/resources/admin/ClientInitialAccessResource.java:84]: > @michalvavrik Just curious, if the `create` method only returns `Response` type, why should the return type of the method still be `Object` ?

It limits changes to the necessary ones, which makes backports easier. Refactoring to Admin API v1 is not important as we are working on v2. You don't need to follow my suggestion, if you disagree, keep it.

File: integration/admin-client/src/main/java/org/keycloak/admin/client/resource/ClientInitialAccessResource.java (hunk 1 above)
Comment (ThreeMangoTrees) [reply integration/admin-client/src/main/java/org/keycloak/admin/client/resource/ClientInitialAccessResource.java]: Thank you for the feedback, @shawkins.

  I have addressed both points:

  1. Reverted the breaking change — the create() method on ClientInitialAccessResource is back to returning ClientInitialAccessPresentation unchanged. All test files that were updated to call .readEntity() have also been reverted. Existing callers of the Java client are unaffected.
  2. Added doCreate() as suggested — a separate method returning the raw Response has been added to the interface: Response doCreate(ClientInitialAccessCreatePresentation rep);
  3. This gives callers who need HTTP-level details (status code, Location header) an escape hatch without touching the existing create() method.
  4. Test updated to use doCreate() — the new test testCreateReturns201WithLocationHeader now uses doCreate() through the typed Java client to assert the 201 Created status and the presence of the Location header, which is exactly what the server-side fix introduced.

Comment (michalvavrik) [reply integration/admin-client/src/main/java/org/keycloak/admin/client/resource/ClientInitialAccessResource.java]: I don't understand why should we enhance client API just for testing purposes. Showing users `create` and `doCreate`, do we have some user scenario where users care about response status? if not, you can test response status using plain HTTP request instead of the REST client.

Comment (ThreeMangoTrees) [reply integration/admin-client/src/main/java/org/keycloak/admin/client/resource/ClientInitialAccessResource.java]: @michalvavrik You're right. `doCreate` was added following @shawkins's suggestion as an alternative to avoid the breaking change, but it has no real user scenario. It exists purely for the test assertion. I've removed it and rewritten `testCreateReturns201WithLocationHeader` to  use a plain HTTP POST via `CloseableHttpClient`, asserting the 201 status and Location header directly on the raw response without going through the typed REST client.

Comment (ThreeMangoTrees) [reply integration/admin-client/src/main/java/org/keycloak/admin/client/resource/ClientInitialAccessResource.java]: @michalvavrik , @shawkins can I get approval now?

File: integration/admin-client/src/main/java/org/keycloak/admin/client/resource/ClientInitialAccessResource.java [hunk 3]
```diff
@@ -40,7 +40,7 @@ public interface ClientInitialAccessResource {
     @Consumes(MediaType.APPLICATION_JSON)
     @Produces(MediaType.APPLICATION_JSON)
     ClientInitialAccessPresentation create(ClientInitialAccessCreatePresentation rep);
-    
+
```
Comment (michalvavrik) [inline integration/admin-client/src/main/java/org/keycloak/admin/client/resource/ClientInitialAccessResource.java]: Let's drop this change, it is just a noise.

File: tests/base/src/test/java/org/keycloak/tests/admin/InitialAccessTokenResourceTest.java [hunk 4]
```diff
@@ -154,6 +175,39 @@ public void testInvalidParametersWhileCreatingInitialAccessTokens() {
...
+            assertNotNull(location, "Location header must be present on 201 Created");
+
+            ClientInitialAccessPresentation entity = JsonSerialization.readValue(
+                    response.getEntity().getContent(), ClientInitialAccessPresentation.class);
+            id = entity.getId();
+            assertNotNull(id);
+            assertNotNull(entity.getToken());
+            assertThat(location, endsWith("/clients-initial-access/" + id));
+        }
+        resource.delete(id);
```
Comment (michalvavrik) [inline tests/base/src/test/java/org/keycloak/tests/admin/InitialAccessTokenResourceTest.java]: I am not sure about this pattern. I thought this should  be done roughly like `id=null` and here `if (id != null) { resource.delete(id); }`  because for example if `assertThat(location, endsWith("/clients-initial-access/" + id));` failed while the entity was created, this test would still have side-effects.

**Review by michalvavrik — COMMENTED** [review]
Almost there, thanks for your patience.

File: integration/admin-client/src/main/java/org/keycloak/admin/client/resource/ClientInitialAccessResource.java (hunk 1 above)
Comment (shawkins) [reply integration/admin-client/src/main/java/org/keycloak/admin/client/resource/ClientInitialAccessResource.java]: The other part of this change is to at least add more javadocs to the get / set status methods so that this doesn't happen again.

Comment (ThreeMangoTrees) [reply integration/admin-client/src/main/java/org/keycloak/admin/client/resource/ClientInitialAccessResource.java]: Updated javadocs for the `get/set` status methods.

File: tests/base/src/test/java/org/keycloak/tests/admin/InitialAccessTokenResourceTest.java (hunk 4 above)
Comment (ThreeMangoTrees) [reply tests/base/src/test/java/org/keycloak/tests/admin/InitialAccessTokenResourceTest.java]: Makes sense. I edited the change.

**Review by michalvavrik — APPROVED** [review]
`services/src/main/java/org/keycloak/services/resources/admin/ClientInitialAccessResource.java` and the test changes  as solution for the one issue we know of LGTM.

I am not sure about javadoc and the javadoc being solution for a general bug that is under this `HttpResponse` status functionality. I'd not document something referring to 200 unless I have a test that:

1. the javadoc regarding 200 is still true in the future as Quarkus side can change
2. I had tests for every other relevant status code so that I know it really is 200/201 only bug
3. I had upstream bug tracker

but I am with this PR based on the 2 files which are fixing https://github.com/keycloak/keycloak/issues/49185 and @shawkins will review the rest (like javadoc he requested 😄 )

File: server-spi/src/main/java/org/keycloak/http/HttpResponse.java [hunk 5]
```diff
@@ -26,13 +26,22 @@
  */
 public interface HttpResponse {
     /**
-     * Gets a status code.
+     * Gets the current status code.
+     *
+     * <p><strong>Warning:</strong> when a JAX-RS resource method returns a plain object (not a
+     * {@link jakarta.ws.rs.core.Response}), the JAX-RS runtime overwrites any status code set here
+     * with 200. To return a non-200 status reliably, return a
+     * {@link jakarta.ws.rs.core.Response} built with the desired status.
```
Comment (shawkins) [inline server-spi/src/main/java/org/keycloak/http/HttpResponse.java]:
```suggestion
     * <p><strong>Warning:</strong> this will typically not be the actual status returned as that will be managed by JAX-RS based upon the return value or exception from the endpoint method.
```

File: server-spi/src/main/java/org/keycloak/http/HttpResponse.java [hunk 6]
```diff
@@ -26,13 +26,22 @@
...
      */
     int getStatus();
 
     /**
      * Sets a status code.
      *
+     * <p><strong>Warning:</strong> this value is silently overwritten by the JAX-RS runtime when
+     * the resource method returns a plain object instead of a {@link jakarta.ws.rs.core.Response}.
+     * Use {@link jakarta.ws.rs.core.Response#status(int)} to set the status reliably.
+     *
```
Comment (shawkins) [inline server-spi/src/main/java/org/keycloak/http/HttpResponse.java]:
```suggestion
     * <p><strong>Warning:</strong> this value is silently overwritten by the JAX-RS runtime based upon the return value or exception from the endpoint method. Please use a JAX-RS compatible way of setting the status instead.
     *
```

**Comment by ThreeMangoTrees** [comment]
> `services/src/main/java/org/keycloak/services/resources/admin/ClientInitialAccessResource.java` and the test changes as solution for the one issue we know of LGTM.
> 
> I am not sure about javadoc and the javadoc being solution for a general bug that is under this `HttpResponse` status functionality. I'd not document something referring to 200 unless I have a test that:
> 
> 1. the javadoc regarding 200 is still true in the future as Quarkus side can change
> 2. I had tests for every other relevant status code so that I know it really is 200/201 only bug
> 3. I had upstream bug tracker
> 
> but I am with this PR based on the 2 files which are fixing #49185 and @shawkins will review the rest (like javadoc he requested 😄 )

@shawkins waiting for your approval.

**Review by shawkins — APPROVED** [review]
> @shawkins waiting for your approval.

Separated off the deprecation task https://github.com/keycloak/keycloak/issues/49374 so that this PR is more suitable for backport if needed.

Thanks @ThreeMangoTrees
